nuntium/templates/nuntium/profiles/messages_per_instance.html
this closes #387.
@martinszy are the explanations ok? if not could you help us with a bit of feedback?
=> Adding explanation for when a message is public, moderated and confirmed

nuntium/templates/nuntium/profiles/messages_per_instance.html
=> Changing the text for better explanation of the publicity of a message 

mailit/bin/handleemail.py, mailit/management/commands/handleemail.py, mailit/migrations/0004_auto__add_rawincomingemail.py, mailit/migrations/0005_auto__add_field_rawincomingemail_writeitinstance__add_field_rawincomin.py, mailit/migrations/0006_auto__add_field_rawincomingemail_message_id.py, mailit/models.py, mailit/tests/incoming_mail_test.py, mailit/tests/save_raw_email_tests.py, nuntium/models.py, nuntium/tests/outbound_message_test.py
related to #439, what is still missing:
=> Store all raw email

.gitignore
ignore files related to Vagrant
=> Add vagrant files to .gitignore

nuntium/models.py, nuntium/views.py
simplify Confirmation.is_comfirmed and MessageDetailView.get_object
=> Small Refactorings

nuntium/templates/nuntium/profiles/your-instances.html
Remove unused Javascript; add missing th text; remove unneeded text
=> Tidy "Your instances"

.travis.yml, requirements.txt
It should be fine to update to the latest security release of Django, I think.
I'm also trying removing a couple of lines which I don't think are used from travis.xml. We'll see what happens.
=> Update django version

nuntium/user_section/tests/user_section_views_tests.py, nuntium/user_section/views.py
Don't merge this yet, I just want to see what travis has to say about something.
=> WIP Intermittent 404 rather than 302

nuntium/migrations/0043_auto__add_field_writeitinstancepopitinstancerecord_autosync.py, nuntium/models.py, nuntium/tasks.py, nuntium/tests/popit_writeit_relation_tests.py, nuntium/tests/tasks_test.py, nuntium/tests/writeitinstances_test.py
The autosync feature is set to True by default
=> This allows for a writeit instance not to automatically sync from popit issue #480

nuntium/templates/nuntium/instance_detail.html, nuntium/templates/nuntium/profiles/contacts/contacts-per-writeitinstance.html, nuntium/templates/nuntium/profiles/messages_per_instance.html, nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html, nuntium/templates/nuntium/profiles/your-instances.html, nuntium/templates/nuntium/template_list.html, nuntium/user_section/tests/manually_create_answers_tests.py, nuntium/user_section/tests/popit_instance_update_tests.py, nuntium/user_section/tests/user_section_views_tests.py, nuntium/user_section/views.py, requirements.txt, writeit/settings.py
=> Adding pagination to a lot of places

nuntium/popit_api_instance.py, nuntium/tests/fixtures/other_people_with_popolo_emails.js, nuntium/tests/writeitinstance_newform_tests.py
=> Creates emails from contacts in popit and relates them to a writeit instance

nuntium/admin.py, nuntium/forms.py, nuntium/tests/writeitinstance_newform_tests.py
=> Accept main popit urls issue 418

mailit/__init__.py, mailit/tests/plugin_test.py, nuntium/migrations/0049_auto__add_field_writeitinstanceconfig_custom_from_domain__add_field_wr.py, nuntium/migrations/0050_auto__chg_field_writeitinstanceconfig_email_use_tls__chg_field_writeit.py, nuntium/models.py, nuntium/tests/confirmation_test.py, nuntium/tests/instance_config_tests.py, nuntium/tests/moderation_messages_test.py, nuntium/tests/subscribers_test.py
=> Using custom email config per instance if given

nuntium/templates/nuntium/profiles/breadcrumbs.html, nuntium/templates/nuntium/profiles/contacts/contacts-per-writeitinstance.html, nuntium/templates/nuntium/profiles/messages_per_instance.html, nuntium/templates/nuntium/profiles/templates.html, nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html, nuntium/templates/nuntium/profiles/writeitinstance_check_delete.html, nuntium/templates/nuntium/profiles/your-instances.html, nuntium/templates/nuntium/writeitinstance_advanced_update_form.html, nuntium/templates/nuntium/writeitinstance_update_form.html
=> Adding links for getting from the edition( admin section) to the front end

nuntium/templates/nuntium/message/message_detail.html, nuntium/templates/nuntium/message/message_in_list.html
=> Adding the date and time of the message and closes #438

nuntium/templates/nuntium/profiles/message_detail.html, nuntium/user_section/tests/manually_create_answers_tests.py
=> Add list of recipients to message admin page.

.gitignore, scripts/provision.sh
=> Add missing vagrant dependencies

mailit/migrations/0009_unrepr_template_strings.py, nuntium/migrations/0058_unrepr_template_strings.py
Replace all the template strings with unrepr'd versions of themselves
where it doesn't cause an error.
=> Unrepr the email templates.

nuntium/popit_api_instance.py, nuntium/tests/fixtures/persons_with_memberships.js, nuntium/tests/popit_api_instance_tests.py
If any Membership is still active, then they should be enabled. This should probably close #419.
=> Extracting from popit adds basic logic to enable or disable contacts.

nuntium/forms.py, nuntium/subdomain_urls.py, nuntium/templates/base_public.html, nuntium/templates/nuntium/instance_detail.html, nuntium/templates/thread/message.html, nuntium/templates/write/draft.html, nuntium/templates/write/preview.html, nuntium/templates/write/sign.html, nuntium/templates/write/who.html, nuntium/urls.py, nuntium/views.py, writeit/settings.py
=> Updated write a message workflow

nuntium/models.py, nuntium/subdomain_urls.py, nuntium/templates/base_instance.html, nuntium/templates/nuntium/message/message_detail.html, nuntium/templates/nuntium/message/message_in_list.html, nuntium/templates/nuntium/message/per_person.html, nuntium/templates/nuntium/profiles/message_detail.html, nuntium/templates/thread/all.html, nuntium/templates/thread/message.html, nuntium/templates/thread/read.html, nuntium/templates/thread/to.html, nuntium/templates/write/preview.html, nuntium/user_section/views.py, nuntium/views.py
Try and get all the list of message pages looking consistent.
Fixes #638
=> Standard display for messages

nuntium/static/sass/manager/_style.scss, nuntium/templates/nuntium/profiles/contacts/contacts-per-writeitinstance.html, nuntium/templates/nuntium/profiles/contacts/show_contacts_in.html
This makes ```manage/recipients/``` much easier to digest
=> Design recipients screen

nuntium/subdomain_urls.py, nuntium/templates/nuntium/profiles/messages_per_instance.html, nuntium/urls.py, nuntium/user_section/tests/hide_a_message_tests.py, nuntium/user_section/tests/user_section_views_tests.py, nuntium/user_section/views.py
This adds the ability for an admin to change the visibility of a message from  ```public``` to  ```hidden```.
=> 585 hide a message

mailit/tests/handle_mails_management_command_test.py, nuntium/templatetags/nuntium_tags.py, nuntium/tests/confirmation_test.py, nuntium/tests/home_view_tests.py, nuntium/tests/message_detail_view_test.py, nuntium/tests/messages_per_person_view_test.py, nuntium/tests/writeitinstances_test.py, nuntium/user_section/tests/documentation_tests.py, nuntium/user_section/tests/hide_a_message_tests.py, nuntium/user_section/tests/template_tags_tests.py, nuntium/user_section/views.py, nuntium/views.py
This improves flake8 and coverage for a couple of missing lines
=> Improving flake8

nuntium/templates/nuntium/instance_detail.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/678
Fixes https://github.com/ciudadanointeligente/write-it/issues/716
=> Don't offer a writing interface if read-only or no contacts

nuntium/templates/thread/message.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/745
=> Show date on the message thread page

nuntium/templates/nuntium/profiles/your-instances.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/651
=> Remove API url from your instances page

nuntium/templates/nuntium/profiles/your-instances.html
On the list of your instances display whether the instance is in testing
mode or not.
Fixes https://github.com/ciudadanointeligente/write-it/issues/578
=> Show if instance if in testing mode on your instances

nuntium/templates/nuntium/profiles/messages_per_instance.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/721
=> Message list show cross icons and change text

nuntium/templates/thread/answer.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/769
=> Show dates on responses on message thread

nuntium/templates/nuntium/profiles/messages_per_instance.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/719
=> Add missing tooltips on messages list page

nuntium/templates/write/breadcrumb.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/762
=> Link back to earlier stages of message writing process

nuntium/user_section/stats.py, nuntium/user_section/tests/stats_page_tests.py
=> Stats descriptions

nuntium/templates/base.html, nuntium/templates/base_manager.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/768
=> Use the instance name in title tags if it exists

nuntium/templates/nuntium/profiles/your-profile.html
This doesn't work properly, so until it does we're just hiding it
completely.
Fixes https://github.com/ciudadanointeligente/write-it/issues/608
=> Comment out password field on profile editing

nuntium/user_section/tests/popit_instance_update_tests.py, nuntium/user_section/views.py
Fixes https://github.com/ciudadanointeligente/write-it/issues/723
=> Redirect back to sources after adding a new source

nuntium/views.py
Fixes https://github.com/ciudadanointeligente/write-it/issues/799
=> Fix order of recent messages on instance detail

nuntium/static/sass/manager/_bootstrap.scss, nuntium/templates/nuntium/profiles/your-instances.html
Make both the name and the link go to the public site, then the edit
button goes to the manager view.
Fixes https://github.com/ciudadanointeligente/write-it/issues/802
Fixes https://github.com/ciudadanointeligente/write-it/issues/800
=> Combine link and name column on your instances

nuntium/templates/thread/read.html
Fixes https://github.com/ciudadanointeligente/write-it/issues/746
=> Add some extra context to the message thread page

nuntium/templates/nuntium/writeitinstance_api_docs.html
=> Remove breadcrumbs from /manage/settings/api page

nuntium/templates/nuntium/message/from_person.html, nuntium/templates/thread/all.html, nuntium/templates/thread/message.html, nuntium/views.py
Fixes https://github.com/ciudadanointeligente/write-it/issues/795
=> Layout for and links to message from person page

nuntium/templates/nuntium/profiles/message_detail.html, nuntium/user_section/views.py
Part of https://github.com/ciudadanointeligente/write-it/issues/738 (and closes #586)
=> Improve manage message detail page

mailit/tests/handle_mails_management_command_test.py, nuntium/migrations/0062_update_confirmation_template_again.py, nuntium/models.py, nuntium/templates/nuntium/mails/confirmation/content_template.txt, nuntium/tests/confirmation_template_test.py, nuntium/tests/confirmation_test.py, nuntium/user_section/stats.py
=> Confirmation email template fixes

nuntium/views.py
Fixes https://github.com/ciudadanointeligente/write-it/issues/810
=> Fix KeyError when creating a new message

nuntium/tests/moderation_messages_test.py, nuntium/views.py
=> Hide a message rather than deleting it when moderation has been rejected

nuntium/templates/nuntium/profiles/templates.html
=> Adding a missing </form> tag

nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html
In the Source Manager, show the update frequency without needing to click the ‘Edit’ button. Closes #853
=> Show update frequency

nuntium/static/sass/instance/_bootstrap.scss, nuntium/static/sass/instance/_layout-thread.scss, nuntium/static/sass/instance/_variables.scss, nuntium/static/sass/manager/_bootstrap.scss, nuntium/templates/pagination/pagination.html, nuntium/templates/thread/all.html, writeit/settings.py
=> Bootstrap styling for Django pagination on thread/all.html

nuntium/subdomain_urls.py, nuntium/templates/nuntium/profiles/welcome.html, nuntium/user_section/tests/user_section_views_tests.py, nuntium/user_section/views.py
This is the basic template for the welcome page. Needs populating with content but that'll get done in a separate pull request.
Part of #922
=> Welcome page

nuntium/templates/thread/read.html, nuntium/templates/write/draft.html, nuntium/templates/write/preview.html
Text tweaks from @MyfanwyNixon to the Message Composer process.
Draft, Before:
After:
---
Preview, before:
After:
---
Message Sent, before:
After:
Closes #734
=> Message Composer text

nuntium/templates/nuntium/instance_detail.html, nuntium/user_section/forms.py
Based on Myf’s text: “Write to the people who represent you. In public. Get answers. In public.”
Closes #741
=> Change default strapline

nuntium/templates/nuntium/profiles/welcome.html, nuntium/user_section/views.py
New copy on the welcome page 
(Note to self: haven't included any config settings explicitly, could do so? I think they need passing in via the view if so.)
=> 922 welcome page text

nuntium/templates/nuntium/profiles/welcome.html
If you have people who are contactable, link to the Test Site to start contacting them:
=> Link from Welcome Page to your Test Site

nuntium/templates/write/draft.html
Added translate string and hint for Your name. Fixes #1003
=> Translate string and adding hint for 'Your name' fixing #1003

nuntium/templates/nuntium/create_new_writeitinstance.html, nuntium/user_section/forms.py
New text from Myf, plus use Javascript to autofill a slug for them based on the domain from
their PopIt.
=> Improve creation process

nuntium/templates/js/poll_pulling.js, nuntium/templates/nuntium/profiles/welcome.html, nuntium/templates/nuntium/writeitinstance_update_form.html
On the Welcome page, do the same “Poll to see when we’re doing pulling
in from Popit” checks as we do on the “About Your Site” page.
Closes #992
=> Poll the pulling status on the Welcome page

nuntium/templates/nuntium/mails/confirmation/subject_template.txt, nuntium/tests/confirmation_template_test.py, nuntium/tests/confirmation_test.py
=> Remove WriteIt from confirmation email subject

nuntium/static/sass/manager/_layout.scss
=> Styling for admin footer

config_examples/.forward.example, config_examples/handle_emails.sh
For files ```handle_emails.sh``` and  the exim ```.forward```
=> Adding config examples

nuntium/templates/base.html, nuntium/templates/base_manager.html, nuntium/templates/google_analytics.html
Make sure we set `campaignName` for subdomains in base.html as well as base_manager.html.
=> Set Google Analytics campaignName in base.html

locale/es/LC_MESSAGES/django.po
This is just the landing page.
=> Adding basic spanish translation

locale/hu/LC_MESSAGES/django.po
Hungarian translations from marietta le
=> Add Hungarian translations

writeit/templates/subdomains/infoszab/about.html
Marietta's translation of the hungarian about page
=> Hungarian translation of about page

locale/hu/LC_MESSAGES/django.po
=> Updated Hungarian translations

writeit/templates/subdomains/infoszab/about.html
As per Marietta's new changes.
=> Changed first three paragraphs of about page

nuntium/popit_api_instance.py, nuntium/tests/fixtures/vcr_cassettes/persons_with_null_values.yaml, nuntium/tests/popit_api_instance_tests.py, requirements_testing.txt
If for some reason the value in the email field is null then this PR can deal with. Previously it was causing an error in the importer.
=> Accepting extra values from popit api

writeit/settings.py
=> trailing slash added to login redirect

nuntium/views.py
This uses the popit/popolo ID as that will be known externally.
=> Go direct to drafting when given person ID in URL.

nuntium/subdomain_urls.py, nuntium/tests/message_creation_tests.py, nuntium/tests/messages_per_person_view_test.py, nuntium/views.py
=> Link direct to person

README.md
=> Add note to README about starting a celery worker for contact syncing

nuntium/templates/base_manager.html, nuntium/templates/nuntium/profiles/message_detail.html, nuntium/templates/nuntium/profiles/messages_per_instance.html, nuntium/templates/nuntium/profiles/your-instances.html
Avoids duplicating the code across individual templates
Fixes #886
=> Put tooltip activation javascript in base admin template

README.md, scripts/provision.sh
- Update the README section about celery worker to remove the reference to PopIt.
- Add a new README section about celery beat, which is needed to send emails to politicians.
- Tell user how to run celery beat in vagrant box
=> Better celery docs

writeit/templates/subdomains/afghanistan/about.html
Paragraphs where assumed should be!
=> Changing the about page text to alpaca text

writeit/templates/subdomains/afghanistan/base_instance.html
Remove the logo from the write-link style and re-add the logo in as a new
link to instance-detail
Fixes mysociety/alpaca#17
=> Change site logo to link to home page

nuntium/templates/thread/read.html, nuntium/tests/moderation_messages_test.py, nuntium/views.py, writeit/templates/subdomains/afghanistan/thread/read.html
If you directly access a message's page then hide the message if it has
not been moderated.
=> hide messages that have not been moderated

nuntium/tests/messages_per_person_view_test.py, nuntium/tests/see_all_messages_from_a_person_tests.py, nuntium/views.py
Make sure the we aren't displaying unmoderated message on the "all messages from this person".
Also add a test to the "all messages to" tests to check for this as well.
Fixes mysociety/alpaca#24
=> Hide unmoderated messages on from page

nuntium/templates/base_manager.html, writeit/settings.py
A few changes to make WriteInPublic work over https.
Related to #451
=> WIP: Allow the site to be served over https

locale/ar/LC_MESSAGES/django.po, locale/cs/LC_MESSAGES/django.po, locale/cs_CZ/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/fa/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/hu/LC_MESSAGES/django.po, nuntium/user_section/forms.py
This pull request:
* Adds some new Farsi translations
* Replaces implicitly generated form labels with translatable ones
* Updates the source line numbers in the .po files
* Use the standard msgfmt wrapping of some of the translated strings
=> Miscellaneous translation updates
