- nuntium/forms.py
- nuntium/templates/nuntium/instance_detail.html
- nuntium/tests/message_form_test.py
- nuntium/tests/writeitinstances_test.py
As part of #436, for now simply remove the public/private tickbox on the new message form.
> Remove ability to send private messages

- nuntium/templates/nuntium/profiles/your-profile.html
The ‘Save Profile’ button doesn’t do anything, so until it does, let’s
just hide it.
> Stop pretending you can edit your profile

- mailit/tests/save_raw_email_tests.py
There's an intermittent test failure of
test_it_relates_to_an_answer_using_web_answer_creation
with the postgres backend.
The problem is in the mocking up of the API call - you can't just
pick item 0 from the list of people related to a message
and expect it to always be the same person - you need to find
the right person, which in this case is the person who's
a member of the WriteItInstance (I think - I'm finding it a
bit hard to get my head round the concept of how all these
models relate to each other).
There are several other intermittent failures. When looking for
a solution to them I think it would be worth looking out for
[0] on a queryset. Unless the queryset is ordered, this gives
back an arbitrary item. Probably many occurrences of this really
need replacing with calls to …
> Fix intermittent test failure.

- nuntium/templates/nuntium/profiles/messages_per_instance.html
The answer count in the messages per instance template needed
pluralizing.
Fixes #424.
> Pluralize answer count in messages per instance.

- nuntium/templates/nuntium/message/message_in_list.html
Replace some custom pluralization code with a call to
blocktrans with a plural section. This will allow translators
in languages with a dual/other plural forms to translate
properly.
> Use standard pluralization rather than custom.

- nuntium/templates/nuntium/profiles/per_instance_top_menu.html
Swap 'Contacts' and 'Templates' so that all of the things to edit
are to the left. Also shorten the name of the 'Contacts' tab.
> Reorder instance edit top menu

- nuntium/templates/nuntium/instance_detail.html
- nuntium/tests/writeitinstances_test.py
If there are no available contacts, say that there is no-one to
write to rather than displaying a form for creating a message.
Obviously this all needs design tidying up.
Fixes #401.
> No message creation form if no contacts.

- nuntium/admin.py
This is a very simple PR which adds to the administration part a ModelAdmin for managing the ConfirmationTemplates, that was missing.
> Adding an admin for Confirmation Template

- .gitignore
- README.md
- Vagrantfile
- requirements.txt
- scripts/provision.sh
This includes:
* Simple Vagrantfile with NFS shared directory
* Provisioning script with zero-input django migrations
* Removal of PostgreSQL-specific package (psycopg2) in requirements.txt
* Documentation in README.md
* Steps to run webserver also printed out on SSH login
Vagrant file tested on a Mac. Can't see any reason why it wouldn't also work on Linux.
@duncanparkes – is there any other setup that the Vagrant provisioner could do, to get people up and running quicker?
> Add a Vagrantfile for running WriteIt in a Vagrant VM

- requirements.txt
This forces django-celery-transactions version to be < 0.2.0 in order to avoid  celery-haystack#36 and #597
> According to celery-haystack#36 this should fix #597

- nuntium/static/sass/instance/_layout-message.scss
- nuntium/templates/nuntium/instance_detail.html
- nuntium/templates/thread/message_mini.html
- nuntium/views.py
This is the same as #641 but against `master` instead of `new_designs`.
---
Fixes #638.
Shown above:
1. A thread where the original message is the thing we're interested in.
2. A thread where one of the replies is the thing we're interested in.
3. A thread where there are no replies (so by default we're interested in the original message).
> mini thread widget styling

- global_test_case.py
- mailit/tests/plugin_test.py
- nuntium/models.py
- nuntium/templates/base_instance.html
- nuntium/templates/nuntium/confirm.html
- nuntium/templates/nuntium/message/message_detail.html
- nuntium/templates/nuntium/message/message_in_list.html
- nuntium/templates/nuntium/profiles/create_answer.html
- nuntium/templates/nuntium/profiles/message_delete_confirm.html
- nuntium/templates/nuntium/profiles/message_detail.html
- nuntium/templates/nuntium/profiles/messages_per_instance.html
- nuntium/templates/nuntium/profiles/update_answer.html
- nuntium/tests/answer_attachments_tests.py
- nuntium/tests/answers_search_test.py
- nuntium/tests/confirmation_template_test.py
- nuntium/tests/confirmation_test.py
- nuntium/tests/home_view_tests.py
- nuntium/tests/messages_per_person_view_test.py
- nuntium/tests/messages_search_test.py
- nuntium/tests/see_all_messages_from_a_person_tests.py
- nuntium/tests/subscribers_test.py
- nuntium/tests/writeitinstances_test.py
- nuntium/user_section/tests/delete_an_instance_tests.py
- nuntium/user_section/tests/documentation_tests.py
- nuntium/user_section/tests/manually_create_answers_tests.py
- nuntium/user_section/tests/popit_instance_update_tests.py
- nuntium/user_section/tests/stats_page_tests.py
- nuntium/user_section/tests/user_section_views_tests.py
- nuntium/user_section/views.py
- nuntium/views.py
This PR fixes several tests broken mostly due to urls.
This is done by overriding the behaviour of  ```client``` attribute of the TestCase by assigning the ```subdomain``` to the request.
> Fix tests after subdomains

- nuntium/static/sass/instance/_layout-message.scss
- nuntium/static/sass/instance/_layout-results.scss
- nuntium/static/sass/instance/_layout-thread.scss
- nuntium/static/sass/instance/_layout-write.scss
- nuntium/static/sass/instance/_layout.scss
- nuntium/static/sass/instance/_style.scss
- nuntium/static/sass/instance/_variables.scss
- nuntium/templates/base.html
- nuntium/templates/thread/all.html
- nuntium/templates/thread/read.html
- nuntium/templates/write/preview.html
The "All messages" page, with an example of the sort of stuff we might put in the sidebar:
(The "Search" page, once it's done, could use this *exact same template*, since it's basically the same thing – a list of messages.)
The "Thread" page:
The "Preview message" page:
The homepage (that middle section still needs some work!! But it's out of scope for now):
> Design tweaks, mostly for message styling

- nuntium/templates/thread/all.html
This hides the filters and search form in the ```/threads``` page.
> Commenting out filtering and searching in the threads part.

- nuntium/templates/nuntium/instance_detail.html
This removes the ```Showing most popular recipients``` part until further notice.
> Removing the part for showing most popular recipients.

- nuntium/templates/thread/message.html
This stops it appearing as one big paragraph in the message preview.
Fixes #736 
Fixes #737
> Convert linebreaks to br tags in message partial

- nuntium/static/sass/instance/_layout-header.scss
- nuntium/templates/base_instance.html
Closes #732.
Includes removing "A WriteIt Instance" from next to the instance name, removing the "Search" and "Sign in" links, adding a "Send a message" link, and tidying up the spacing of icons in the user dropdown menu.
> Clean up header/nav content

- nuntium/templates/base_instance.html
The doubling of "any messages you send will be sent" is a tiny bit jarring. Change it to "any messages you write will be sent".
> Tweak wording of Test Mode banner

- nuntium/templates/write/draft.html
- nuntium/views.py
This shows who you're writing to on the draft screen, which will become
important once we link directly to the draft screen from a person page.
Fixes #648
> Add a list of recipients to the draft screen

- nuntium/static/sass/instance/_layout-write.scss
- nuntium/templates/write/draft.html
- nuntium/templates/write/preview.html
Includes a subtle reminder on the Writing page, and a very prominent reminder on the Preview page.
@tmtmtmtm or @MyfanwyNixon might want to tweak the wording.
Fixes #730.
> Remind users that their message will be made public

- nuntium/models.py
Because the subject line is read from a file it contains a newline, we
need to strip this otherwise the email library will throw an error.
Fixes https://github.com/ciudadanointeligente/write-it/issues/775
> Strip newlines from subject before sending

- nuntium/templates/thread/all.html
If the instance doesn't contain any public messages then show a message
informing the user that this is the case.
Fixes https://github.com/ciudadanointeligente/write-it/issues/727
> Display message when there are no public messages

- nuntium/tests/message_creation_tests.py
- nuntium/views.py
This would set for each form in WriteMessageView a prefix so we can
avoid sharing forms across instances. 
Fixes #715
> Adding a form_prefix to the for the forms in the message creation wizard

- nuntium/templates/thread/all.html
The comment here points at the wrong Issue: we can put this back when we have public search, which is different from the admin side filtering.
> Thread boxes depend on public search, not Admin

- nuntium/templates/write/breadcrumb.html
- nuntium/templates/write/draft.html
- nuntium/templates/write/who.html
Depending on how the instance is configured the correct pluralisation of
recipients should be done.
Fixes https://github.com/ciudadanointeligente/write-it/issues/765
> Fix pluralisation depending on instance max recipients

- nuntium/templates/thread/answer.html
Fixes #750.
Sorry, can't make a screenshot, but it's dead simple. The "To" line in a reply is gone now, leaving just the "From" (ie: the politician) and their message content.
> Remove "To" from the way we display message replies

- nuntium/templates/thread/all.html
This will probably need a bit of design from @zarino 
Part of https://github.com/ciudadanointeligente/write-it/issues/714 (but still needs design)
> Paginate the list of all messages for an instance

- nuntium/user_section/stats.py
On the stats page it doesn't make sense to show a count of public
messages and total messages if there are no private messages and
therefore the counts are the same.
Fixes https://github.com/ciudadanointeligente/write-it/issues/808
> Only show total public messages if there are private ones

- nuntium/static/sass/instance/_layout-person.scss
- nuntium/static/sass/instance/_layout-results.scss
- nuntium/static/sass/instance/_layout-write.scss
- nuntium/templates/thread/to.html
- nuntium/templates/write/draft.html
Now looks like:
Fixes #754. Also fixes #639. And improves the styling of the "To" field introduced in #759 since I was in the vacinity.
> Lots of fixes for the person page

- nuntium/user_section/forms.py
- nuntium/user_section/tests/popit_instance_update_tests.py
When an admin tries to re-add a PopIt that is already linked, don't just show an error message, but instead repoll. Per discussion at https://github.com/ciudadanointeligente/write-it/pull/812#issuecomment-91229834
> Repoll when admin re-adds a pre-existing PopIt

- Vagrantfile
- scripts/provision.sh
This pull request
- ~~Ports the provisioning script to [Ansible](http://docs.ansible.com/) for idempotent provisioning~~ This doesn't work if the user doesn't have ansible installed locally, so sticking with a shell script for now.
- Adds postfix so emails can be sent from the VM
- Adds nodejs and mongodb packages so that the tests run successfully "out of the box".
- Adds extra details to motd.tail about loading fixture data and running the tests
- Uses virtualenv to isolate pip dependencies
- Increases vagrant memory to 1GB
> Add missing vagrant dependencies

- nuntium/static/sass/instance/_layout-message.scss
- nuntium/templates/thread/answer.html
Fixes #830.
Untested with real data. But should look like:
> Reinstate message attachment links on read.html page

- nuntium/templates/nuntium/profiles/your-instances.html
Add a new 'Recipients' column to the Site Manager:
Closes #831
> Site Manager: Add link to Recipients page

- nuntium/static/sass/instance/_layout-thread.scss
- nuntium/templates/thread/read.html
I noticed [this](https://github.com/ciudadanointeligente/write-it/blob/650bc976141d480d74fb53361be9dd2c54fdc93a/nuntium/templates/thread/read.html#L39) crept in over the last two days, and looked a bit rushed.
This change styles the message so that it looks more like a placeholder for a reply.
> Styling for "future replies" message on thread page

- nuntium/templates/nuntium/writeitinstance_update_form.html
- nuntium/user_section/forms.py
- nuntium/user_section/tests/user_section_views_tests.py
rate_limit should always be above zero.
I’ve added the server-side validation for this, but can’t work out yet how to add an equivalent client-side check to the one on maximum_recipients.
Fixes #840
> Disallow negative rate_limits

- nuntium/forms.py
Add `’required’: True` to all the widgets of the Message writing form
so that we get HTML5 client-side validation, as well as the server-side
validation that already exists.
Closes #820
> Make all Message fields compulsory

- nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html
If we have a status_explanation for the polling status, show it:
Fixes #728
> 728: Explain import errors

- nuntium/templates/thread/to.html
The form prefixes we added in #790 broke the hidden form we use to “Write to this person” on the Recipient page. We need to add the instance_slug to make it work again. Fixes #856
> Add the instance_slug to the hidden 'Who'

- nuntium/templates/write/who.html
When searching for recipients, show how many you can have. Closes #857
> Show the maximum recipients on the form

- nuntium/views.py
In the “Search for recipients by name” box, order them by name.
Before:
After:
Ideally we’d be able to order by them by their PopIt sort_name, but this is better than not ordering them at all.
Closes #872
> Message Creator: Order contacts by name

- nuntium/user_section/views.py
Ideally this would be by their `sort_name`, or, if we don’t have that, we should really take into account the language code of the linked PopIt. But this will do for now, at least until #752 gives us filtering options.
Before:
After:
Closes #874
> Recipient Manager: Order contacts by name

- nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html
Currently every form in the sources list gets the same ID, so attempting to edit any of them will always give you the first one.
Instead give each a unique id, so that we can edit any of them:
Fixes #851
> Source Manager: Give each form's div a unique id

- nuntium/templates/nuntium/template_list.html
- Add a link to the “Create” page (Fixes #832)
- Change “instances” to “sites” (#530)
- Pull “Test Mode” up to beside the instance name (Fixes #852)
It's still pretty ugly, but #395 will require changing this page substantially anyway.
> Tidy "All Instances" page

- nuntium/templates/nuntium/writeitinstance_update_form.html
On the Site Manager we currently report if we’re actively fetching data for that instance from PopIt:
However, all admin pages already report on this in the header bar.
So replace this message with the inprogress spinner:
(I suspect we should just be including that line of JS on all admin pages, rather than pulling it individually like this, but’s one for another change. #886)
Closes #839
> Remove double flash after site creation

- nuntium/templates/base_instance.html
- nuntium/templates/thread/to.html
- nuntium/templates/write/who.html
**Remove “Send a message” from the header bar**
----
**Remove “Write to this person” from the Recipient page**
----
**Disallow going directly to the message composer**
Closes #887
> 887 When messages are disallowed

- nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html
**NOTE**: This should be merged after 854, as I mistakenly branched off it.
Having the “Fetch new data now” button in-between changing and saving the polling interval is confusing. Move the ‘Save’ button up to beside the interval:
Fixes #722
> Source Manager: Fix confusing buttons

- nuntium/templates/nuntium/profiles/status-bar.html
The “Test Mode” banner should always be above other status messages.
Also, tweak the wording to be more in line with the public-facing
equivalent of it.
Closes #882
> Move the Test Mode banner to the top

- nuntium/templates/base_instance.html
Replace “instance” and “WriteIt” with “Site”.
Also, only show the first message of: “Read Only”, “No Recipients”, “Test Mode” — there’s no point in showing “Test Mode” if either of the others are true.
Closes #889
> 889 Tidy header bar text

- nuntium/forms.py
- nuntium/templates/nuntium/create_new_writeitinstance.html
- nuntium/templates/nuntium/profiles/your-instances.html
- nuntium/tests/writeitinstance_newform_tests.py
- nuntium/user_section/forms.py
Closes #863 
- Make the name and URL both be Required 
- We don't need API URLs — simple PopIt URLs will do
- Use working PopIts as examples
- Don't have a separate Modal form from Sites Manager: just link to the main one
- Use the "Site" terminology instead of WriteIt/Instance
Splitting the form into a two-step process that fetches the Popit's /about page to auto-fill the `name` field doesn't work yet, because CORS. So that half is now #877
> Tidy the "Create a new site" forms

- nuntium/templates/nuntium/profiles/messages_per_instance.html
Make it more obvious that the button actively approves the message. (Closes #583)
Whilst here, add ?s to the text headers (`Moderated?` instead of `Moderated`), move the "number of replies" column further left, and remove needless `WriteIt` name. (Improves #827)
> 583: Improvements to Message Manager

- nuntium/templates/nuntium/profiles/your-instances.html
- nuntium/user_section/views.py
Show the live sites and test sites separately in the Site Manager.
Before:
After:
Only test sites now have a Delete button (see #751)
It’s important for the Test Sites to get some better explanatory text, as the New User journey will involve them only having a single site, in test mode. The current text is just a placeholder that will remind us to create something better.
NB: I don't really like how much duplication there is in the template, and I’m not entirely convinced that the views.py implementation of this is the right way to go about this at all... It's also a little ugly, but the admin design process should hopefully clean that up.
Closes #880
> Split live sites and test sites

- nuntium/templates/nuntium/instance_detail.html
Don’t show a “Recent Messages” section if there are no messages to display in it. 
Closes #866
> Home Page: Hide the "Recent Messages" section if there are none

- nuntium/models.py
- nuntium/subdomain_urls.py
- nuntium/tests/moderation_messages_test.py
- nuntium/tests/writeitinstance_newform_tests.py
- nuntium/user_section/forms.py
- nuntium/user_section/tests/user_section_views_tests.py
- nuntium/user_section/views.py
- nuntium/views.py
Tidy up miscellaneous flake8 problems
The only ones left are in popit-django + one line in an email message in`email_answer_tests.py` that deliberately has a trailing space.
> Fix flake8 warnings

- nuntium/templates/nuntium/profiles/messages_per_instance.html
Add an extra column to the message manager that links to the public page if the message is public and confirmed.
I suspect I also need to check something to do with moderation, but I don’t know how to do that, as message.moderated only seems to be true for messages that have *actively* been moderated, not ones that didn’t _need_ to be moderated. (And if we need that many checks, we should really just add a new 'visible?' method to the message. We also need to solve this problem on the Admin page for the message.)
I’m also not 100% convinced about adding this as a new column, but putting it beside the subject line doesn’t really work as then you have both the internal and external links side by side with no visual distinction between them. But @wrightmartin will be doing more work on this …
> Link to public message page where appropriate

- mailit/__init__.py
> Get rid of duplicate domain and scheme URL in message.

- nuntium/static/sass/manager/_layout.scss
- nuntium/static/sass/manager/_style.scss
- nuntium/templates/nuntium/profiles/contacts/contacts-per-writeitinstance.html
- nuntium/templates/nuntium/profiles/manager-navigation.html
- nuntium/templates/nuntium/profiles/messages_per_instance.html
- nuntium/templates/nuntium/profiles/profile-navigation.html
- nuntium/templates/nuntium/writeitinstance_answernotification_form.html
- nuntium/templates/nuntium/writeitinstance_api_docs.html
- nuntium/templates/nuntium/writeitinstance_autoconfirm_form.html
- nuntium/templates/nuntium/writeitinstance_max_recipients_form.html
- nuntium/templates/nuntium/writeitinstance_moderation_form.html
- nuntium/templates/nuntium/writeitinstance_update_form.html
**THIS IS WIP PLEASE DON'T MERGE**
- Settings are now grouped into pages, and linked from the relevant screen
- Forms with multiple fields have an improved design
- WIP items that will need looking at
- URLS (#936)
- <s>Message settings has multiple fields that aren't set up properly</s>
- Rename template files to reflect their new purpose
- I have left 'Web based form' option in place, as this may be removed
- 'Moderation settings' page is currently orphaned, until the new moderation page is added
> reorganised admin pages for better experience

- writeit/settings.py
See https://docs.djangoproject.com/en/1.6/ref/middleware/#middleware-ordering.
This could cause get_language to produce the wrong language, and perhaps
be the reason why we sometimes get en-us in urls where we don't want it.
I'm not certain this is going to fix the problem, but this is definitely a change that needs to happen, so please merge it anyway.
> CommonMiddleware must come after LocaleMiddleware

- nuntium/templates/nuntium/profiles/status-bar.html
Do we have a useful target to make the "contact us" a link? Who is "us"?
...but as things stand, this is still better than having a link here :-)
> remove link, add 'contact us' note

- nuntium/templates/write/who.html
Explicitly say “You can send your message to up to {{ counter }} people” rather than combining it into “Search for up to {{counter }} recipients by name”.
Or, if you can only send to one person:
Fixes #909
> Better explanation of how many people you can write to

- nuntium/templates/nuntium/profiles/manager-navigation.html
We don’t want to link to Moderation or Rate Limiting for now as they’re not ready for public consumption.
The pages will still exist, so that we can tell people individually (with suitable warnings) that they can use them, but we don’t want to make them obvious to normal admins.
Before:
After:
Closes #927 and #933
> Hide admin links to Moderation and Rate Limiting

- writeit/settings.py
This just adds the actual settings. We also need to actually use these
settings within the creation process etc so that they make the sites
behave in different ways.
Part of https://github.com/ciudadanointeligente/write-it/issues/679
> Add settings for web vs API based sites

- nuntium/templates/nuntium/profiles/manager-navigation.html
- nuntium/templates/nuntium/profiles/profile-navigation.html
- nuntium/templates/nuntium/profiles/your-instances.html
- nuntium/templates/nuntium/writeitinstance_web_based_form.html
Move the “Web Based?” config option to be a “Disable Site” config on the Site Manager instead. 
Before:
After:
Then rename that form to make it more obvious what it's for (we still need better text for that, but we'll be doing all the admin text tomorrow):
Before:
After:
This is the last "Advanced" option so we can now remove that section entirely:
Before:
After:
Closes #751
> 751 Disable Instance

- nuntium/templates/base_instance.html
We no longer have an admin setting for Test Mode, so don’t link to it from the public site.
Before:
After:
Closes #954
> Remove link to Test Mode admin setting

- nuntium/templates/base_instance.html
- nuntium/templates/base_manager.html
- nuntium/templates/base_writeinpublic.html
removing “WriteIt” per #530, but also noting that you’re not going
directly to your Site(s), but to the Manager.
Before:
Back End:
Front End:
After:
Back End:
Front End:
Closes #956
> Change "Your WriteIts" to "Site Manager" in header bar

- nuntium/templates/nuntium/profiles/contacts/contacts-per-writeitinstance.html
The recipient manager still refers to “in your WriteIt”. Clean that up (for #530), remove an obsolete modal from when we could manually add contacts, and link to the Data Sources page when we mention it:
Before:
After:
> Recipient manager wording

- nuntium/templates/nuntium/profiles/message_detail.html
- nuntium/templates/nuntium/profiles/messages_per_instance.html
Currently moderation happens from the Messages page, rather than the
individual Message page. This is bad, as you want to be able to read
the message before moderating it. So move the button to there.
NB: This has all the same problems as the previous version, but but
it’s a slightly better version of broken here, and helps clean the
Messages Manager up a little bit more for other things we want to do
there.
Old:
New:
Closes #904
> Move moderation to the message admin

- nuntium/templates/registration/login.html
- nuntium/templates/registration/signup.html
This means that if you arrive at the login page from another page, e.g. the create new instance page, then you will get redirected back to that page after signing up/in with Google.
Fixes #963
> Pass ?next parameter through to python-social-auth

- nuntium/templates/base_instance.html
If you have contacts in your instance, but none of them have email addresses, show the "No contacts" banner, as it'll get people closer to diagnosing the problem. (I still want to investigate what happens when you have _disabled_ all the contacts, but that's for another change #972 and much less likely to happen than someone connecting a PopIt with no emails). Closes #968 
Also, change the links in these banners to go directly to the relevant settings page, rather than the central admin page. Closes #966 
Before: (different URLs in bottom left corner when hovering on links)
After:
> 968 no contactable contacts

- nuntium/templates/nuntium/profiles/your-instances.html
In the instance manager, check if an instance is already Disabled before offering a link to disable it.
Before
After
It's a little ugly, but we haven't really solved the "show binary option with ability to change it" problem, so in the absence of design time, this'll have to do for now, especially as it should hopefully be a very rare occurrence.
Fixes #969
Also add new text from @MyfanwyNixon explaining the Test Mode section:
> Show if a site is already disabled

- nuntium/templates/nuntium/profiles/manager-navigation.html
- nuntium/templates/nuntium/writeitinstance_update_form.html
Make it obvious when a PopIt import finishes. 
If you’re on the Admin page for an instance, it shows a spinner if we’re currently fetching data for that instance. But, confusingly, nothing lets you know when that finishes, so you can sit for ages waiting for it to do something.
So have it only spin when the import is still in progress, and then also update the number of users in the sidebar.
(Which requires actually *adding* the number of users to the sidebar (closes #979); and whilst we’re there adding little icons beside each entry. Scope-creep-orama. The dependency management to do these all as separate changes at this point, especially with the afternoon Huboard delay) isn’t worth it.
when finished, automatically becomes:
Closes #908 . We might end up needing to do something similar …
> 908 check import status

- nuntium/subdomain_urls.py
- nuntium/templates/about.html
- nuntium/templates/base_instance.html
- nuntium/views.py
Add the text @MyfanwyNixon wrote for the About page (with chunks of it hidden, pending future features). 
We still need to add the bottom "How you can get a site like this too" section.
After some discussion about the best way to internationalise this, we decided to solve that the first time someone actually wants their own version, as it's more likely that someone will want to change the entire page, rather than translate this paragraph by paragraph.
> About page

- nuntium/templates/nuntium/profiles/welcome.html
We should be checking whether there are contactable persons, not just any persons. If there aren’t, then we can check if it’s because we haven’t loaded _anyone_ yet, or because we couldn’t find email addresses for people.
Closes #990, but more still to do in #992
> More complex logic for "How many people in your instance"

- nuntium/templates/home.html
New copy for front page from @MyfanwyNixon
Before:
After:
The link to view other instances is hidden until we have some web-based ones worth showing. (WriteIt can have its own link/list here, showing off Nouabook etc, but WriteInPublic has nothing to link to yet.)
Closes #931 for now.
> New front page

- nuntium/templates/about.html
Add a section to the About page linking to WriteInPublic so people can
have their own instance (and adding some credits). Closes #999 and fixes #740.
> Add a "How was this site built?" section

- nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html
- nuntium/templates/nuntium/profiles/your-instances.html
The admin section base template already shows all the alert messages —
there’s no need to repeat them within the individual pages as well.
before:
after:
Helps with #967
> Don't double flash messages

- writeit/context_processors.py
- writeit/settings.py
This exposes `WEB_BASED` and `API_BASED` settings to the template so you
can do something like:
{% if WEB_BASED %}
Something
{% endif %}
in the templates.
> Add web_api_settings context processor

- nuntium/templates/nuntium/profiles/status-bar.html
When we talk about “testing mode” link to the Welcome Page, which will
explain it again.
> Link to the Welcome Page from Status Bar

- nuntium/user_section/tests/popit_instance_update_tests.py
- nuntium/user_section/views.py
We don’t need to give a separate flash message about getting people, as
we already have the one that says that we’re actively pulling people.
Closes #967 (in conjunction with #1001)
> Remove the "We are now getting the people from popit" message

- nuntium/templates/base_manager.html
Set the HTML `title`, and the title in the header to either
WriteInPublic or WriteIt based on the settings.
With `API_BASED = True`:
With `WEB_BASED = True`:
Finally closes #530 (hopefully)
> Switch the header and `title` between WriteInPublic and WriteIt

- nuntium/user_section/forms.py
If the user doesn't supply a slug in the site creation process then don't try and validate it and let the ORM automatically choose one.
This was originally supposed to be part of https://github.com/ciudadanointeligente/write-it/pull/988, but got lost when adding validations for the format of the subdomain.
> Don't validate slug if none provided

- nuntium/templates/nuntium/profiles/contacts/contacts-per-writeitinstance.html
- nuntium/templates/nuntium/profiles/manager-navigation.html
- nuntium/templates/nuntium/profiles/your-instances.html
Show different admin pages depending on whether we’re API_BASED or WEB_BASED.
Ideally we’d do this per *instance* rather than per *server*, but that depends on #998, so this will do for now (especially as the pages all still exist in either case, it’s just that the links to them will be hidden).
About :
API_BASED (API link):
WEB_BASED (no API link):
Recipients Manager:
API_BASED:
WEB_BASED:
Sites Manager:
API_BASED:
WEB_BASED:
Closes #996
> Different Web vs API admin pages

- nuntium/templates/base_instance.html
If logged in as the admin, go directly to that site’s admin from header bar, rather than your Sites Manager.
If it’s still in testing mode, go to the welcome page; otherwise the main edit page.
Closes #1016
> Go to site admin from public header

- nuntium/templates/nuntium/profiles/contacts/contacts-per-writeitinstance.html
If the number of contactable people is different from the total number of contacts in your database, it’s useful to see both counts.
Closes #1020
> Show counts for total contacts and contactable people

- nuntium/templates/base_instance.html
In the header bar, if logged in, but viewing someone else’s site, link to your own Sites Manager, instead of that site’s admin.
(It might be nice to see if the person only _has_ one site, and if so link directly to it, but that's overkill for here)
Closes #1022
> Don't link to admin section of other people's sites

- nuntium/templates/nuntium/profiles/your-profile.html
- nuntium/templates/nuntium/writeitinstance_autoconfirm_form.html
Don’t show the API key on the User page — it’ll just confuse most users. Show it on the API Settings page instead for users who _do_ need it, and would naturally look for it there.
before:
after:
Closes #1025
> 1025 move api key

- nuntium/templates/base_manager.html
> Show the Admin's name rather than username in the header

- nuntium/templates/registration/login.html
The sign-up page pretends there’s a sign up page. There isn’t (yet #620). Explain that they need to Sign in with Google instead.
Before:
After:
Closes #1019
> Remove link to non-existent Sign Up page

- nuntium/migrations/0063_blank_new_answer_templates.py
- nuntium/models.py
- nuntium/tests/confirmation_template_test.py
- nuntium/tests/subscribers_test.py
- nuntium/user_section/forms.py
- nuntium/user_section/tests/user_section_views_tests.py
- nuntium/user_section/views.py
- nuntium/views.py
Stop storing default templates for content and subject in the
database for confirmation templates and new answer notification
templates.
The only place I know of where this still happens is the subject
of the actual message from mailit, and the default for this is
{subject}, so I don't think changing it is urgent!
Fixes #898
> Don't store default templates in the db.

- nuntium/templates/nuntium/mails/new_answer.txt
- nuntium/tests/subscribers_test.py
Until we can include an indication of what attachments there are,
let's not include the message content at all.
This should be done after #1028
> Don't include message content in new answer notification.

- contactos/tests/contacts_tests.py
- example_data.yaml
- mailit/tests/email_parser/incoming_mail_tests.py
- nuntium/management/commands/send_mails.py
- nuntium/migrations/0063_add_site_to_outbound_message.py
- nuntium/models.py
- nuntium/tests/outbound_message_test.py
This associates all outbound messages with a `Site` object from the django sites framework. The plan is to then have a separate celery worker for each site which just sends the emails for that specific domain.
Fixes #1033
> Fix links and From: address in emails sent to representatives 

- nuntium/user_section/forms.py
When we check if a proposed slug is already taken, make sure not to ignore case, so if 'eduskunta' is already taken, and someone asks for 'eDuSkUnTa', don’t let them proceed.
Closes #1012
> Check for existing slugs case-insensitively

- nuntium/models.py
The new answer notification email is not sent as a response
to a user request, but rather to an email arriving. Because of this,
we can't set the active language based on the user's browser settings
or cookies, so let's deactivate translation of this url completely.
I'm hoping this will fix #828.
> Deacivate translation for the new answer email url.

- nuntium/subdomain_urls.py
- nuntium/templates/base_manager.html
- nuntium/templates/nuntium/profiles/contact.html
- nuntium/templates/nuntium/profiles/status-bar.html
- nuntium/templates/nuntium/profiles/welcome.html
- nuntium/templates/nuntium/writeitinstance_max_recipients_form.html
- nuntium/user_section/views.py
Add a ‘contact us’ page on the Admin side, and link it up from various places
For now it’s just the team email address — we can make it something more complex later. (Possibly switching on WriteIt vs WriteInPublic too)
Closes #652 
Closes #944
> Admin-side contact us

- nuntium/templates/nuntium/profiles/your-instances.html
On the Message Manager, the Edit button for sites that are in Test Mode currently goes to the basic editor (for name + description). Instead, take them to the Welcome page, which provides more information on the whole process of what to edit.
> Make 'edit' on Test sites go to Welcome

- mailit/__init__.py
- mailit/migrations/0011_rename_variables_without_writeit.py
- mailit/templates/mailit/mails/content_template.txt
- nuntium/migrations/0065_rename_variables_without_writeit.py
- nuntium/models.py
- nuntium/templates/nuntium/mails/confirmation/content_template.txt
- nuntium/templates/nuntium/mails/moderation_mail.txt
- nuntium/templates/nuntium/mails/moderation_subject.txt
- nuntium/templates/nuntium/mails/new_answer.txt
- nuntium/tests/subscribers_test.py
Replace '{writeit_name}' and '{writeit_url}' in message
templates with '{site_name}' and '{site_url}'.
Fixes #1043.
> Rename template variables containing 'writeit'.

- global_test_case.py
- writeit/settings.py
So, in the case in which we point to ```http://chile.writeinpublic.com/en/manage```,
the LOGIN_URL in that case will be forced to be ```http://writeinpublic.com/en/accounts/login```,
rather than ```http://chile.writeinpublic.com/en/accounts/login```, which was returning a 404.
This should close #850.
> This provides a LOGIN_URL forcing it not to use subdomain.

- writeit/settings.py
According to django-haystack/celery-haystack#23 some problems in the server were due to some missing variables in the settings file. Those missing variables are being added in this commit.
> Hotfix solving a problem with the configuration in the servers

- writeit/settings.py
What this does is set the default login url using the default language, which was causing but #1070.
> Bug #1070 wrong create your own instance is broken.

- nuntium/tests/confirmation_test.py
- nuntium/views.py
This instead of raising a 404 error.
Closes #961
> Clicking twice the confirmation url redirects to the message.

- nuntium/templates/base.html
- nuntium/templates/base_manager.html
- writeit/context_processors.py
- writeit/settings.py
This PR:
- Gets the Google Analytics property ID from `local_settings.py` or environment.
- Includes the subdomain as the `name` of the GA tracker and as the `campainName` variable that's sent
> Improve Google Analytics tracking

- writeit/middleware.py
- writeit/settings.py
- writeit/templates/subdomains/infoszab/about.html
This PR provides a middleware that inspects the subdomain for the current
request (as provided by django-subdomains) and inserts an entry for
subdomain-specific templates to settings.TEMPLATE_DIRS if one exists for
that subdomain.
I've not had to implement a custom template loader because `filesystem.Loader` seems to re-evaluate `TEMPLATE_DIRS` for each request, but that might not be the case in installations other than my local setup. It'd be good to have more eyes on this, specifically when `DEBUG = False`.
> Allow templates to be overridden on a subdomain-specific basis

- nuntium/tests/message_creation_tests.py
- nuntium/views.py
If there's a single person with contacts in an instance it automatically selects that person and redirects to the 'draft' step.
> If theres a single contact skip first step

- requirements.txt
Fixing the versions of django-haystack to 2.4.0 and elasticsearch to 1.6.0
@lfalvarez did the work here, I'm just doing the Pull Request :smile:
> Pin pip packages to fix travis tests

- nuntium/forms.py
- nuntium/popit_api_instance.py
- nuntium/templates/nuntium/create_new_writeitinstance.html
- nuntium/user_section/forms.py
- nuntium/user_section/tests/user_section_views_tests.py
- nuntium/user_section/views.py
This allows you to create a site using data pulled from EveryPolitician. It currently does this by giving the user a dropdown list of countries, which are pulled from a proxy app running on heroku. This proxy app then provides a url which WriteInPublic can use to pull EveryPolitician data through an API which looks just like a PopIt API.
Part of #862
> Allow site creation from EveryPolitician data

- nuntium/forms.py
- nuntium/popit_api_instance.py
- nuntium/templates/nuntium/create_new_writeitinstance.html
- nuntium/tests/fixtures/vcr_cassettes/default.yaml
- nuntium/tests/fixtures/vcr_cassettes/other_people_with_popolo_emails.yaml
- nuntium/tests/fixtures/vcr_cassettes/other_persons.yaml
- nuntium/tests/fixtures/vcr_cassettes/person_with_preferred_email_and_contact_detail.yaml
- nuntium/tests/fixtures/vcr_cassettes/persons_with_emails.yaml
- nuntium/tests/fixtures/vcr_cassettes/persons_with_memberships.yaml
- nuntium/tests/fixtures/vcr_cassettes/persons_with_null_values.yaml
- nuntium/user_section/forms.py
- nuntium/user_section/views.py
- requirements.txt
It now accepts as well as a popit-style URL (to which it would add /persons and expect paginated data), a popolo JSON file with direct data in persons. The popolo JSON for people should contain id, name, (email), (image), (summary) and memberships either inline or in separate memberships.
Fix some JS-only/JS errors along the way.
Fixes #1105. Fixes #1111.  Fixes #1106. Might be enough for #862.
~~Test failure is in downloading Django, don't know what that's about; passes locally.~~
> Allow import of Popolo JSON file directly

- scripts/provision.sh
Our version of elasticsearch-py only supports Elasticsearch > 1.x so we need a
newer version. 1.4 is the version of Elasticsearch we're testing against on
Travis so that's the version we should have in Vagrant.
I think this is the right fix instead of what was proposed in my previous closed PR #1121.
> Upgrade version of elasticsearch installed in Vagrant

- README.md
- test.py
When I first created a new Vagrant box I read the readme and it said to run
`./test.py` but that didn't work. Then I noticed in the motd when you login to
the Vagrant box it says to us a different command. This is confusing so this
commit gets rid of that extra command and just documents the one way of running
tests.
Fixes #1117
> Only specify one way of running tests

- requirements.txt
This locks django_admin_bootstrapped at 2.3.6, which is compatible with our
version of Django, 1.6. It means form fields in the admin are actually visible
so you can see and edit them.
Fixes #1123
> Ensure django_admin_bootstrapped is a version compatible with Django

- scripts/provision.sh
The current version of elasticsearch relies on Java 7 and silently fails
to launch which Java 6 so install Open JDK 7
> Update vagrant JDK install to match elasticsearch expected version

- nuntium/models.py
- nuntium/templates/base_instance.html
- nuntium/templates/nuntium/instance_detail.html
- nuntium/templates/thread/to.html
- nuntium/templates/write/who.html
- nuntium/tests/writeitinstances_test.py
- writeit/templates/subdomains/infoszab/nuntium/instance_detail.html
Use this in the templates to determine if we can send messages rather
than checking for contacts and enabled.
Fixes #891
> Add can_create_messages property to instances

- nuntium/templates/nuntium/create_new_writeitinstance.html
Add a link to re-show the legislature list and hide the manual popolo
list.
Fixes #1126
> Allow user to swap back to legislature list on instance create page

- example_data.yaml
- nuntium/middleware.py
- nuntium/migrations/0066_auto__add_field_writeitinstanceconfig_default_language.py
- nuntium/models.py
- nuntium/templates/nuntium/profiles/welcome.html
- nuntium/templates/nuntium/writeitinstance_update_form.html
- nuntium/tests/writeitinstances_test.py
- nuntium/user_section/forms.py
- nuntium/user_section/tests/user_section_views_tests.py
- writeit/settings.py
This adds a piece of middleware which checks the instance for a default language and sets that on the request if there isn't a translation for the users' default language.
Fixes https://github.com/ciudadanointeligente/write-it/issues/1091
> Allow instances to set a default language

- requirements.txt
- requirements_testing.txt
As of django-nose/django-nose@7f205f1b16e641a7b1 support for Django
earlier than 1.7 was dropped, but write-it is still using Django
1.6.10 (which is no longer supported, but that's another issue: #718)
django-nose 1.4.3 is the last version that works with Django 1.6.
> Pin django-nose to the last version that works with Django < 1.7

- .travis.yml
These are much faster to start up than builds on the legacy
infrastructure; the .travis.yml doesn't use sudo anyway, so this should
work fine.
> Switch to using container-based builds on Travis

- README.md
The Elasticsearch API has changed between the major versions 0.x, 1.x
and 2.x, and you need to use a Python package that is compatible.
This update to the README.md hopefully explains how to pick working
versions of both.
> README.md: add help on Elasticsearch versioning

- .tx/config
- README.md
- deploying_to_heroku.md
- locale/cs_CZ/LC_MESSAGES/django.po
- locale/fa/LC_MESSAGES/django.po
- requirements.txt
- scripts/provision.sh
These commits add:
* A dependency on the Transifex command-line client, for convenience
* Two new languages (cs_CZ and fa)
* Uses of `./manage.py compilemessages` that are required for multi-lingual support
> Add extra languages and Transifex configuration

- nuntium/tests/home_view_tests.py
- nuntium/views.py
It's annoying for local development that the redirect that's returned
from '/' is a permanent redirect (301) since then localhost:8000
redirects to, say, http://127.0.0.1.xip.io:8000/en/ even when working
on other sites, meaning you need to clear your browser's redirect cache
(not simple on all browsers).
It seems wrong that this is a permanent redirect anyway, since the
language prefix on the URL depends on Accept-Language, and you might
change languages in your browser.
This commit changes the redirect to 302 Found; widely interpreted as a
temporary redirect.
Fixes #1170
> Redirects from / to a language-specific variant shouldn't be permanent

- nuntium/models.py
- nuntium/tests/moderation_messages_test.py
Prevent an exception being thrown when moderating a message confirmed
before moderation for all messages by creating the moderation object at
moderation time.
Fixes #704
> allow messages created before moderation enabled to be moderated

- nuntium/migrations/0002_fix_bad_datetime_defaults.py
- nuntium/models.py
The default for two DateField fields was now(), which would evaluate to
the current date and time at the point when the class is defined; what's
usually intended is that the default is the function 'now', which will
be evaluted when an instance of the model is created.  This commit makes
that change, including the corresponding migration.
> Fix some DateField defaults (should be 'now', not 'now()')

- scripts/provision.sh
Not sure whether this has been added in the right place, but I needed gettext to make django work in the vagrant vm.
I've also swapped the order of the setup steps in the shell login message, because if you don't load the example data first, django will automatically redirect you to example.com and you'll have no idea why.
> Add gettext dependency to vagrant provision.sh

- example_data.yaml
- nuntium/tests/api/page_paginator_test.py
We would occasionally get failures from the test:
nuntium.tests.api.page_paginator_test:PagePaginationTestCase.test_get_paginated
I believe this is may be because of a couple of problems:
- The messages returned from the API are ordered by their 'created'
attribute, but the messages created from the fixtures had 'created'
set to None. This means they may have been returned in an arbitrary
order.
- The list of public objects used to compare against was not
explicitly ordered, so the order these are returned would have been
arbitrary (well, database-specific anyway) as well.
This commit fixes both of those issues, so that hopefully these
transient test failures won't happen any more.
> Fix intermittent test failures

- nuntium/models.py
- nuntium/templates/nuntium/profiles/messages_per_instance.html
- nuntium/templates/nuntium/profiles/moderation_queue.html
- nuntium/templates/thread/message.html
- nuntium/templates/thread/message_mini.html
- nuntium/templates/write/draft.html
- nuntium/templatetags/nuntium_tags.py
- nuntium/tests/messages_test.py
- nuntium/user_section/tests/template_tags_tests.py
- writeit/templates/subdomains/infoszab/write/draft.html
- writeit/templates/subdomains/iran/nuntium/instance_detail.html
- writeit/templates/subdomains/iran/thread/message.html
- writeit/templates/subdomains/iran/write/draft.html
These are attempted fixes for #26 and a fix for "and" being used
in between the last two elements of a list in non-English
languages.
> More fixes for "comma and 'and'" joining in non-English languages

- nuntium/tests/moderation_messages_test.py
- nuntium/views.py
Fixes the logic for the /read page so we do not hide messages that have been created before the current moderation code and have moderated=None.
Also tidy up the other message views to use the public_objects manager of Message rather than repeating the same filters in multiple place.
> More moderated viewing fixes

- mailit/__init__.py
- mailit/tests/plugin_test.py
- nuntium/models.py
- nuntium/tests/subscribers_test.py
The confirmation email already used the current language
as a language prefix in the URLs. However, the new answer
notification email and the outgoing message email are sent
from other contexts (from celery beat or in response to a
new email arriving) where there is no HTTP request to
provide a preferred language. However, each of these emails
is associated with an instance, and their config has a default
language. These commits make sure that default language
is used in the links in these emails.
> Fix the language prefix of links in emails

- contactos/migrations/0002_contact_popolo_person.py
- contactos/models.py
- instance/migrations/0003_add_parallel_popolo_data.py
- instance/migrations/0004_add_django_popolo_people.py
- instance/models.py
- nuntium/migrations/0003_add_parallel_popolo_data.py
- nuntium/models.py
- requirements.txt
- writeit/settings.py
This is the first part of: https://github.com/ciudadanointeligente/write-it/pull/1181 for review. See that pull request for the context for this pull request.
It adds django-popolo models in parallel with the popit-django models that we're intending to replace.
> Migration to django-popolo part 1

- contactos/migrations/0003_denull_popolo_people.py
- contactos/migrations/0004_remove_contact_person.py
- contactos/migrations/0005_rename_migrated_fields.py
- contactos/models.py
- global_test_case.py
- instance/migrations/0005_denull_popolo_source.py
- instance/migrations/0006_remove_old_fields.py
- instance/migrations/0007_rename_migrated_fields.py
- instance/migrations/0008_remove_writeitinstancepopitinstancerecord_popitapiinstance.py
- instance/models.py
- nuntium/admin.py
- nuntium/migrations/0003_denull_popolo_people.py
- nuntium/migrations/0004_remove_old_fields.py
- nuntium/migrations/0005_rename_migrated_fields.py
- nuntium/models.py
- writeit/settings.py
This is the second part of: #1181 for review. See that pull request for the context for this pull request.
This removes the old popit-django model references.
> Migration to django-popolo part 2

- nuntium/templates/nuntium/message/message_detail.html
- nuntium/templates/nuntium/message/message_in_list.html
- nuntium/templates/nuntium/profiles/message_detail.html
- nuntium/templates/thread/answer.html
- nuntium/templates/thread/message.html
- nuntium/templates/thread/message_mini.html
- nuntium/templatetags/nuntium_tags.py
- nuntium/tests/date_localization_tests.py
- requirements.txt
- writeit/templates/subdomains/iran/thread/answer.html
- writeit/templates/subdomains/iran/thread/message.html
This uses the Khayyam Python package to convert datetimes to the Jalali
calendar.
> Use the Jalali calendar for datetime rendering in Persian

- .tx/config
- locale/ar/LC_MESSAGES/django.po
- locale/ar/LC_MESSAGES/djangojs.po
- locale/cs/LC_MESSAGES/django.po
- locale/cs/LC_MESSAGES/djangojs.po
- locale/cs_CZ/LC_MESSAGES/django.po
- locale/cs_CZ/LC_MESSAGES/djangojs.po
- locale/en/LC_MESSAGES/django.po
- locale/en/LC_MESSAGES/djangojs.po
- locale/es/LC_MESSAGES/django.po
- locale/es/LC_MESSAGES/djangojs.po
- locale/fa/LC_MESSAGES/django.po
- locale/fa/LC_MESSAGES/djangojs.po
- locale/fr/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/djangojs.po
- locale/hu/LC_MESSAGES/django.po
- locale/hu/LC_MESSAGES/djangojs.po
- nuntium/forms.py
- nuntium/static/js/who.js
- nuntium/static/sass/instance/_bootstrap.scss
- nuntium/static/sass/instance/_layout-write.scss
- nuntium/static/sass/instance/_style.scss
- nuntium/static/sass/instance/_variables.scss
- nuntium/subdomain_urls.py
- nuntium/templates/write/missing_contacts.html
- nuntium/templates/write/who.html
- nuntium/tests/message_form_tests.py
- nuntium/views.py
- writeit/templates/subdomains/iran/write/missing_contacts.html
- writeit/templates/subdomains/iran/write/who.html
After this pull request, people without email addresses are also offered as possible selections to write to. They are clearly marked as such, and users are given the option of either removing that recipient, or going to a page which lists all such people and appeals to the user to help in finding those email addresses. Here's @zarino's nice animation of the new selection process:
Things still to do:
> Handle people who are missing email addresses more elegantly

- nuntium/static/sass/manager.scss
- nuntium/static/sass/manager/_variables.scss
- nuntium/templates/nuntium/profiles/templates.html
- nuntium/templates/nuntium/profiles/writeitinstance_and_popit_relations.html
Two template files referenced {% static 'css/chosen.css' %}, which was
removed in 6009225cbb23f46f.  That causes errors in production when
loading pages base on those templates.
That earlier commit switched to using bootstrap's styling for
the chosen.js-enhanced UI elements; this commit does the same to replace
the chosen.css references that are left.
> Replace the broken references to chosen.css

- instance/migrations/0003_add_name_and_email_match_config_option.py
- instance/models.py
- nuntium/tests/see_all_messages_from_a_person_tests.py
- nuntium/views.py
There is a view ('all-messages-from-the-same-author-as') which, given a
message slug, allows you to list any other messages with the same author
email address as the message with that slug. In situations where anonymity
is important, this is undesirable - someone might send a sensitive message
with a false name and an uncontroversial one with their real name, in
which case this view would reveal that they're sent by the same person.
This commit introduces a new instance config option
('email_and_name_must_match') which means that the
'all-messages-from-the-same-author-as' view will only show messages that
have the same author_email *and* author_name, to avoid this information
leak.
Fixes mysociety/alpaca#35
Fixes ciudadanointeligente/write-it#1194
> Add an instance config option for stricter anonymity

- instance/migrations/0004_add_email_real_name_to_config.py
- instance/models.py
- nuntium/models.py
- nuntium/templates/nuntium/writeitinstance_answernotification_form.html
- nuntium/tests/confirmation_test.py
- nuntium/tests/subscribers_test.py
- nuntium/user_section/forms.py
- nuntium/user_section/tests/user_section_views_tests.py
We had complaints from partner that the confirmation emails from the
site appeared to be from 'belgium-reps', say, in your mail client if
the email was From: belgium-reps@example.com
To address this problem, this commit adds an instance configuration
setting for the real name that should be used in the From: line of
confirmation emails and answer notification emails.  (This can be
any unicode string, and it will be encoded sensibly by Django's
smtp backend.)
> Allow a custom "real name" in From: line from some site emails

- nuntium/templates/nuntium/profiles/message_detail.html
The message detail pages that you see in the site owner's admin were
offering "Accept" or "Reject" moderation options even when the message
hadn't been confirmed yet.  People were clicking on these which would
then generate user-facing error pages and notify us of the error by
email.  This commit changes the message detail page to only offer those
options for confirmed messages.
> Don't offer moderation buttons for unconfirmed messages

- instance/migrations/0013_fix_record_auto_updated_field.py
- instance/models.py
- nuntium/tests/popit_writeit_relation_tests.py
auto_now_add=True only sets the date when the object is first created,
which is only suitable for the 'created' field. auto_now=True is the
correct option for 'updated'.
This pull request also contains a commit to make sure that the
'inprogress' status is set however syncing is initiated, and one to remove
some unnecessary code.
> An 'updated' DateTimeField should use auto_now, not auto_now_add

- mailit/bin/handleemail.py
- mailit/exceptions.py
- mailit/management/commands/handleemail.py
- mailit/tests/fixture/temporary.txt
- mailit/tests/handle_mails_management_command_test.py
If we get a temporary failure message then ignore it as we only need to
do something if the failure is permanent.
> raise and handle exception on temporary mail failure

- instance/management/commands/instance_remove_extraneous_popolo_uri.py
- instance/models.py
- instance/tests/test_remove_extraneous_ids.py
- requirements.txt
We were getting duplicate identifiers on each resync with scheme='popolo_uri'.
This pull request fixes that.
Fixes mysociety/alpaca#60
> Fixes for multiple popolo_uri Identifier objects

- scripts/provision.sh
I needed to add this package to get `vagrant up` working correctly. I'm
not entirely sure why this wasn't needed before, perhaps it was in a
previous version of the base box but was subsequently removed?
> Install gettext in vagrant box
